second_clone/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(
        r'^login/$', auth_views.LoginView.as_view(
            template_name='accounts/login.html'
        ),
        name='login'
    ),
    url(
        r'^logout/$', auth_views.LogoutView.as_view(),
        name='logout'
    ),
    url(
        r'^signup/$', views.SignUp.as_view(),
        name='signup'
    ),
]

second_clone/groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.ListGroups.as_view(), name='all'),
    url(r'^new/$', views.CreateGroup.as_view(), name='create'),
    url(
        r'^posts/in/(?P<slug>[-\w]+)/$',
        views.SingleGroup.as_view(),
        name='single'
    ),
]

second_clone/posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'^new/$', views.CreatePost.as_view(), name='create'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPost.as_view(),
        name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(),
        name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

second_clone/second_clone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.Homepage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

second_clone/accounts/models.py
from django.db import models
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

second_clone/groups/models.py
from django.db import models
from dajngo.utils.text import slugify
from django.core.urlresolvers import reverse

# Create your models here.
import misaka  ## link embedding

from django.contrib.auth import get_user_model
User = get_user_model()
from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'groups:single',
            kwargs={'slug': self.slug}
        )

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='meberships')
    user = models.ForeignKey(User, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

second_clone/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

import misaka

from second_clone.groups import models as group_models

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(
        group_models.Group, related_name='Posts', null=True, blank=True
    )

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'posts:single',
            kwargs={
                'username': self.user.username,
                'pk': self.pk
            }
        )

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

second_clone/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

second_clone/accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.core.urlresolvers import reverse_lazy

from . import forms


# Create your views here.
class Homepage(TemplateView):
    template_name = 'index.html'


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


class TestPage(TemplateView):
    template_name = 'test.html'


class ThanksPage(TemplateView):
    template_name = 'thanks.html'

second_clone/groups/views.py
from django.shortcuts import render

# Create your views here.
from dajngo.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin
)
from django.core.urlresolvers import reverse
from django.views import generic

from . import models


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = models.Group


class SingleGroup(generic.DetailView):
    """docstring for SingleGroup"""

    model = models.Group


class ListGroups(generic.ListView):
    """docstring for ListGroups"""

    model = models.Group

second_clone/posts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin
from . import models, forms

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    """docstring for PostList"""
    model = models.Post
    select_related = ('user', 'group')


class UserPosts(generic.ListView):
    """docstring for UserPosts"""
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            # trying to set the user which belongs to this particular post
            # equal to the user post objects which have the same username
            # as this user
            # in other words it tries to get all the posts which were posted
            # by this particular logged in user
            self.post_user = User.objects.prefetch_related('posts').get(
                username__iexact=self.kwargs.get('username')
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user

        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    """docstring for PostDetail"""
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get('username')
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    """docstring for CreatePost"""
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    """docstring for DeletePost"""
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user_id=self.request.user.id
        )

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

second_clone/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <h1>Log In</h1>

        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Log In" class"btn btn-primary">
        </form>
    </div>
{% endblock content %}

second_clone/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <h1>Sign Up</h1>

        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                {% endbuttons %}
        </form>
    </div>
{% endblock content %}

second_clone/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock pregroup %}
            {% block group_content %}{% endblock group_content %}
            {% block postgroup %}{% endblock postgroup %}
        </div>
    </div>
{% endblock content %}

second_clone/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <h1>{{ group.name }}</h1>
    <h2>Member count: {{ group.members.count }}</h2>

    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-warning"><span class"fa fa-times-circle"> </span>Leave group</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-primary"><span class"fa fa-hand-o-right"> </span>Join group</a>
        {% endif %}
    </div>
{% endblock pregroup %}

{% block group_content %}
    <div class="col-md-8">
        {% for post in group.post.all %}
            {% include "posts/_post.html" %}
        {% empty %}
            <p>No posts yet!</p>
        {% endfor %}
    </div>
{% endblock group_content %}

second_clone/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
    <h4>Create a new group</h4>

    <form action="{% url 'groups:create' %}" method="post" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn bnt-primary btn-large" value="Create">
    </form>
{% endblock group_content %}

second_clone/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome back! <a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a></h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page</p>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="fa fa-pencil"> </span>Create New Group!</a>
        {% endif %}
    </div>
{% endblock pregroup %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
                    <h3 class="title list-group-item-heading">{{ group.name }}</h3>
                    <div class="list-group-item-text container-fluid">
                        {{ group.description_html|safe }}
                        <div class="col-med-4">
                            <span class="badge">{{ group.members.count }}</span>
                            member{{ group.members.count|pluralize }}
                        </div>
                        <div class="col-md-4">
                            <span class="badge">
                                {{ group.posts.count }}
                            </span>
                            post{{ group.posts.count|pluralize }}
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock group_content %}

second_clone/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static "second_clone/css/master.css" %}">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse mynav" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#">Post</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Group</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Create Group</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
              {% else %}
                <li class="nav-item"><a class="nav-link" href="#">Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
              {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

second_clone/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to star social!</h1>
{% endblock content %}

second_clone/templates/test.html
{% extends "base.html" %}

{% block content %}
    <h1>You are now logged in!</h1>
{% endblock content %}

second_clone/templates/thanks.html
{% extends "base.html" %}

{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>
{% endblock content %}